on:
  push:
    branches: 
      - master





jobs:
  build:
    runs-on: ubunto-latest


    steps:
      # - name: 'testing github actions'
      #   run: pwd
      # - name: 'testing print'
      #   run: echo ahmed

      - name: 'printing folder content'
        run: ls
      
